#!/bin/bash
set -e

# Upload Go stdlib registries to Cloudflare R2
#
# Usage: ./upload_go_stdlib_to_r2.sh [temp_dir]
#
# Each Go version's registry is generated by pointing the extractor at that
# version's GOROOT.  In CI the GOROOTs are captured from successive
# `actions/setup-go` steps and passed as environment variables:
#
#   GOROOT_1_18=/path/to/go1.18
#   GOROOT_1_19=/path/to/go1.19
#   ...
#
# The generator itself is compiled with the currently active (latest) Go so
# that it satisfies the module's go.mod requirement.

GO_VERSIONS=("1.18" "1.19" "1.20" "1.21" "1.22" "1.23" "1.24" "1.25" "1.26")
TEMP_DIR="${1:-/tmp/cpf-go-stdlib-registries}"
R2_BUCKET="code-pathfinder-assets"

# ---------------------------------------------------------------------------
# Validate R2 credentials
# ---------------------------------------------------------------------------
if [ -z "$R2_ACCOUNT_ID" ] || [ -z "$R2_ACCESS_KEY_ID" ] || [ -z "$R2_SECRET_ACCESS_KEY" ]; then
    echo "Error: Missing R2 credentials"
    echo "Required environment variables:"
    echo "  - R2_ACCOUNT_ID"
    echo "  - R2_ACCESS_KEY_ID"
    echo "  - R2_SECRET_ACCESS_KEY"
    exit 1
fi

# Configure AWS CLI for R2
export AWS_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY"
R2_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

echo "========================================="
echo "Go Stdlib Registry Generation & Upload"
echo "========================================="
echo "Temp directory : $TEMP_DIR"
echo "R2 Bucket      : $R2_BUCKET"
echo "R2 Endpoint    : $R2_ENDPOINT"
echo "Compiler Go    : $(go version)"
echo ""

mkdir -p "$TEMP_DIR"

# Resolve the sast-engine module root (one level above this script's directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Generate and upload a registry for each Go version
# ---------------------------------------------------------------------------
UPLOADED=()
SKIPPED=()

for version in "${GO_VERSIONS[@]}"; do
    echo "========================================="
    echo "Processing Go $version"
    echo "========================================="

    # Convert "1.18" -> "GOROOT_1_18" for indirect variable expansion
    env_var="GOROOT_$(echo "$version" | tr '.' '_')"
    goroot="${!env_var}"

    if [ -z "$goroot" ]; then
        echo "Warning: $env_var is not set, skipping Go $version"
        SKIPPED+=("$version")
        echo ""
        continue
    fi

    if [ ! -d "$goroot/src" ]; then
        echo "Warning: $goroot/src not found for Go $version, skipping"
        SKIPPED+=("$version")
        echo ""
        continue
    fi

    OUTPUT_DIR="$TEMP_DIR/registries/go${version}/stdlib/v1"
    mkdir -p "$OUTPUT_DIR"

    # Step 1: generate
    echo "Step 1/3: Generating stdlib registry (GOROOT=$goroot)..."
    # -tags ignore is required because the file carries //go:build ignore to
    # exclude it from normal package builds; go run still respects that tag
    # in Go 1.17+ unless we explicitly satisfy it via -tags.
    (cd "$MODULE_DIR" && go run -tags ignore tools/generate_go_stdlib_registry.go \
        --go-version  "$version" \
        --goroot      "$goroot" \
        --output-dir  "$OUTPUT_DIR")

    echo ""
    echo "Step 2/3: Verifying generated files..."

    if [ ! -f "$OUTPUT_DIR/manifest.json" ]; then
        echo "Error: manifest.json not generated for Go $version"
        exit 1
    fi

    FILE_COUNT=$(ls -1 "$OUTPUT_DIR"/*.json | wc -l | tr -d ' ')
    TOTAL_SIZE=$(du -sh "$OUTPUT_DIR" | cut -f1)
    echo "  ✓ Generated $FILE_COUNT JSON files ($TOTAL_SIZE total)"

    # Step 3: upload
    echo ""
    echo "Step 3/3: Uploading to R2..."
    aws s3 sync "$OUTPUT_DIR" \
        "s3://$R2_BUCKET/registries/go${version}/stdlib/v1/" \
        --endpoint-url "$R2_ENDPOINT" \
        --delete \
        --content-type  "application/json" \
        --cache-control "public, max-age=3600"

    echo "  ✓ Uploaded Go $version registry"
    UPLOADED+=("$version")
    echo ""
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "========================================="
echo "Upload Complete!"
echo "========================================="

if [ ${#UPLOADED[@]} -gt 0 ]; then
    echo ""
    echo "Uploaded versions:"
    for version in "${UPLOADED[@]}"; do
        echo "  https://assets.codepathfinder.dev/registries/go${version}/stdlib/v1/manifest.json"
    done
fi

if [ ${#SKIPPED[@]} -gt 0 ]; then
    echo ""
    echo "Skipped versions (GOROOT not available): ${SKIPPED[*]}"
fi

# Clean up default temp directory
if [ "$TEMP_DIR" = "/tmp/cpf-go-stdlib-registries" ]; then
    echo ""
    echo "Cleaning up temp directory..."
    rm -rf "$TEMP_DIR"
    echo "  ✓ Cleaned up $TEMP_DIR"
fi

echo ""
echo "Done!"
