# action.yml
name: 'Code-Pathfinder OSS'
description: 'Code-Pathfinder open-source alternative to CodeQL'
inputs:
  command:
    description: 'Command to run'
    required: true
    default: 'ci'
  project:
    description: 'Source code to scan'
    required: true
    default: ${{ github.workspace }}
  rules-directory:
    description: 'Rules directory'
    required: false
  ruleset:
    description: 'Predefined rules eg: cpf/java'
    required: false
  output:
    description: 'Output format eg: json'
    required: false
    default: 'json'
  output-file:
    description: 'Output file'
    required: false
    default: 'output.json'
runs:
  using: 'docker'
  image: 'shivasurya/code-pathfinder:dev-0.0.28'
  args:
    - ${{ inputs.command }}
    - --project
    - ${{ inputs.project }}
    - --ruleset
    - ${{ inputs.ruleset }}
    - --output
    - ${{ inputs.output }}
    - --output-file
    - ${{ inputs.output-file }}
