package registry

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/shivasurya/code-pathfinder/sast-engine/graph/callgraph/core"
)

// CppStdlibRegistryRemote is the C++ counterpart to CStdlibRegistryRemote.
// Same dual-mode structure, but exposes class- and method-level accessors
// the C interface does not have.
//
// We could compose by embedding CStdlibRegistryRemote, but that would force
// the URL path to use `c/v1` instead of `cpp/v1`. Defining a parallel struct
// keeps the URL/cache paths language-correct at the cost of ~30 LoC of
// near-duplicate file:// and cache plumbing — an acceptable tradeoff for
// clarity.
type CppStdlibRegistryRemote struct {
	baseURL  string
	platform string
	fileBase string

	manifest    *core.CStdlibManifest
	headerCache map[string]*core.CStdlibHeader
	cacheMutex  sync.RWMutex

	httpClient *http.Client
	diskCache  *diskCacheStore
}

// NewCppStdlibRegistryFile constructs a file:// loader for C++ stdlib JSON.
// localPath is the directory containing manifest.json + the per-header files
// generated by PR-01.
func NewCppStdlibRegistryFile(localPath, platform string) *CppStdlibRegistryRemote {
	return &CppStdlibRegistryRemote{
		platform:    platform,
		fileBase:    localPath,
		headerCache: make(map[string]*core.CStdlibHeader),
	}
}

// NewCppStdlibRegistryRemote constructs an HTTP loader. PR-03 fills in the
// network path; PR-02 keeps the constructor for API stability.
func NewCppStdlibRegistryRemote(baseURL, platform string) *CppStdlibRegistryRemote {
	cacheRoot := getStdlibCacheRoot()
	var dc *diskCacheStore
	if cacheRoot != "" {
		dc = newDiskCacheStore(filepath.Join(cacheRoot, platform, "cpp", "v1"))
	}
	return &CppStdlibRegistryRemote{
		baseURL:     strings.TrimSuffix(baseURL, "/"),
		platform:    platform,
		headerCache: make(map[string]*core.CStdlibHeader),
		httpClient:  &http.Client{Timeout: 30 * time.Second},
		diskCache:   dc,
	}
}

// LoadManifest reads the top-level manifest.json over file:// or HTTPS.
// HTTP failures fall back to the on-disk cache regardless of TTL so an
// offline scan still resolves stdlib calls when a previous run populated
// the cache.
func (r *CppStdlibRegistryRemote) LoadManifest(logger core.CStdlibLogger) error {
	if r.fileBase != "" {
		return r.loadManifestFromFile(logger)
	}
	return r.loadManifestFromHTTP(logger)
}

// loadManifestFromHTTP is the C++ counterpart to the C loader's HTTP path.
// The URL layout is identical except for the language segment ("/cpp/v1/"
// instead of "/c/v1/").
func (r *CppStdlibRegistryRemote) loadManifestFromHTTP(logger core.CStdlibLogger) error {
	url := joinURL(r.baseURL, r.platform, "cpp", "v1", "manifest.json")
	if logger != nil {
		logger.Debug("Downloading C++ stdlib manifest: %s", url)
	}

	data, err := fetchURL(r.httpClient, url)
	if err != nil {
		if cached, cerr := r.diskCache.GetManifest(); cerr == nil {
			if logger != nil {
				logger.Warning("Network failed for %s; serving cached manifest. Underlying: %v", url, err)
			}
			r.cacheMutex.Lock()
			r.manifest = cached
			r.cacheMutex.Unlock()
			return nil
		}
		return fmt.Errorf("loadManifestFromHTTP: %w", err)
	}

	var manifest core.CStdlibManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return fmt.Errorf("loadManifestFromHTTP: parsing manifest from %s: %w", url, err)
	}

	if cerr := r.diskCache.SaveManifest(data); cerr != nil && logger != nil {
		logger.Warning("Failed to save C++ manifest to disk cache: %v", cerr)
	}

	r.cacheMutex.Lock()
	r.manifest = &manifest
	r.cacheMutex.Unlock()

	if logger != nil {
		logger.Statistic("Loaded C++ stdlib manifest over HTTP: %d headers for %s",
			len(manifest.Headers), r.platform)
	}
	return nil
}

func (r *CppStdlibRegistryRemote) loadManifestFromFile(logger core.CStdlibLogger) error {
	path := filepath.Join(r.fileBase, "manifest.json")
	data, err := os.ReadFile(path) //nolint:gosec // path is operator-supplied via CLI flag
	if err != nil {
		return fmt.Errorf("loadManifestFromFile: reading %s: %w", path, err)
	}
	var manifest core.CStdlibManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return fmt.Errorf("loadManifestFromFile: parsing %s: %w", path, err)
	}
	r.cacheMutex.Lock()
	r.manifest = &manifest
	r.cacheMutex.Unlock()
	if logger != nil {
		logger.Statistic("Loaded C++ stdlib manifest from file: %d headers for %s",
			len(manifest.Headers), r.platform)
	}
	return nil
}

// GetHeader returns the per-header content with the same double-check-locked
// caching as the C loader.
func (r *CppStdlibRegistryRemote) GetHeader(name string) (*core.CStdlibHeader, error) {
	r.cacheMutex.RLock()
	if h, ok := r.headerCache[name]; ok {
		r.cacheMutex.RUnlock()
		return h, nil
	}
	r.cacheMutex.RUnlock()

	r.cacheMutex.Lock()
	defer r.cacheMutex.Unlock()

	if h, ok := r.headerCache[name]; ok {
		return h, nil
	}
	h, err := r.fetchHeaderLocked(name)
	if err != nil {
		return nil, err
	}
	r.headerCache[name] = h
	return h, nil
}

func (r *CppStdlibRegistryRemote) fetchHeaderLocked(name string) (*core.CStdlibHeader, error) {
	if h, ok := r.headerCache[name]; ok {
		return h, nil
	}
	if r.manifest == nil {
		return nil, errors.New("fetchHeaderLocked: manifest not loaded; call LoadManifest first")
	}
	entry := r.manifest.GetHeaderEntry(name)
	if entry == nil {
		return nil, fmt.Errorf("fetchHeaderLocked: header %q not in stdlib manifest", name)
	}

	if r.fileBase != "" {
		return r.fetchHeaderFromFile(entry)
	}
	return r.fetchHeaderFromHTTP(entry)
}

// fetchHeaderFromHTTP downloads one per-header JSON over HTTP. Mirrors
// the C loader's strategy: disk-cache freshness on the way in, stale-cache
// fallback on network failure, optional checksum verification.
func (r *CppStdlibRegistryRemote) fetchHeaderFromHTTP(entry *core.CStdlibHeaderEntry) (*core.CStdlibHeader, error) {
	if r.diskCache.IsFresh(entry.File, stdlibCacheTTL) {
		if cached, err := r.diskCache.GetHeader(entry.File); err == nil {
			return cached, nil
		}
	}

	url := r.headerURL(entry)
	data, err := fetchURL(r.httpClient, url)
	if err != nil {
		if cached, cerr := r.diskCache.GetHeader(entry.File); cerr == nil {
			return cached, nil
		}
		return nil, fmt.Errorf("fetchHeaderFromHTTP: %w", err)
	}

	if err := verifyChecksum(data, entry.Checksum); err != nil {
		return nil, fmt.Errorf("fetchHeaderFromHTTP: %s: %w", entry.Header, err)
	}

	var h core.CStdlibHeader
	if err := json.Unmarshal(data, &h); err != nil {
		return nil, fmt.Errorf("fetchHeaderFromHTTP: parsing %s: %w", url, err)
	}

	_ = r.diskCache.SaveHeader(entry.File, data) // best-effort

	return &h, nil
}

// headerURL prefers the manifest-embedded URL when present and falls back
// to <baseURL>/<platform>/cpp/v1/<file> for manifests that predate the
// per-entry URL field.
func (r *CppStdlibRegistryRemote) headerURL(entry *core.CStdlibHeaderEntry) string {
	if entry.URL != "" {
		return entry.URL
	}
	return joinURL(r.baseURL, r.platform, "cpp", "v1", entry.File)
}

func (r *CppStdlibRegistryRemote) fetchHeaderFromFile(entry *core.CStdlibHeaderEntry) (*core.CStdlibHeader, error) {
	path := filepath.Join(r.fileBase, entry.File)
	data, err := os.ReadFile(path) //nolint:gosec // path is operator-supplied via CLI flag
	if err != nil {
		return nil, fmt.Errorf("fetchHeaderFromFile: reading %s: %w", path, err)
	}
	var h core.CStdlibHeader
	if err := json.Unmarshal(data, &h); err != nil {
		return nil, fmt.Errorf("fetchHeaderFromFile: parsing %s: %w", path, err)
	}
	return &h, nil
}

// GetFunction looks up a free or top-level function by bare name. For
// namespaced free functions (std::move), the resolver should use
// GetFreeFunction with the full FQN.
func (r *CppStdlibRegistryRemote) GetFunction(headerName, funcName string) (*core.CStdlibFunction, error) {
	h, err := r.GetHeader(headerName)
	if err != nil {
		return nil, err
	}
	if f, ok := h.Functions[funcName]; ok {
		return f, nil
	}
	if f, ok := h.FreeFunctions[funcName]; ok {
		return f, nil
	}
	return nil, fmt.Errorf("GetFunction: %q not in header %q", funcName, headerName)
}

// GetClass returns the class metadata for the given fully-qualified class
// name within the named header. Returns an error when the class is absent
// (callers treat this as a "try the next include" signal).
func (r *CppStdlibRegistryRemote) GetClass(headerName, classFQN string) (*core.CppStdlibClass, error) {
	h, err := r.GetHeader(headerName)
	if err != nil {
		return nil, err
	}
	cls, ok := h.Classes[classFQN]
	if !ok {
		return nil, fmt.Errorf("GetClass: %q not in header %q", classFQN, headerName)
	}
	return cls, nil
}

// GetMethod is a two-step accessor: GetClass + look up the method by bare
// name. The receiver type's template arguments are NOT substituted here —
// the caller is responsible for that, since substitution depends on the
// concrete receiver instance (e.g. vector<int> vs vector<string>).
func (r *CppStdlibRegistryRemote) GetMethod(headerName, classFQN, methodName string) (*core.CStdlibFunction, error) {
	cls, err := r.GetClass(headerName, classFQN)
	if err != nil {
		return nil, err
	}
	if m, ok := cls.Methods[methodName]; ok {
		return m, nil
	}
	return nil, fmt.Errorf("GetMethod: %q not in class %q", methodName, classFQN)
}

// GetFreeFunction looks up a namespaced free function by its full FQN
// (e.g. "std::move", "std::swap"). Distinct from GetFunction so the resolver
// can be explicit about which form it expects.
func (r *CppStdlibRegistryRemote) GetFreeFunction(headerName, fqn string) (*core.CStdlibFunction, error) {
	h, err := r.GetHeader(headerName)
	if err != nil {
		return nil, err
	}
	if f, ok := h.FreeFunctions[fqn]; ok {
		return f, nil
	}
	return nil, fmt.Errorf("GetFreeFunction: %q not in header %q", fqn, headerName)
}

// Platform returns the platform tag for this registry.
func (r *CppStdlibRegistryRemote) Platform() string {
	return r.platform
}

// HeaderCount returns the total number of headers in the loaded manifest.
func (r *CppStdlibRegistryRemote) HeaderCount() int {
	r.cacheMutex.RLock()
	defer r.cacheMutex.RUnlock()
	if r.manifest == nil {
		return 0
	}
	return len(r.manifest.Headers)
}

var _ core.CppStdlibLoader = (*CppStdlibRegistryRemote)(nil)
