package diagnostic

// FunctionMetadata contains all information about a function needed for diagnostic analysis.
type FunctionMetadata struct {
	// FilePath is the relative path to the source file
	// Example: "myapp/views.py"
	FilePath string

	// FunctionName is the simple function name
	// Example: "process_input"
	FunctionName string

	// FQN is the fully qualified name (module.Class.function)
	// Example: "myapp.views.process_input" or "myapp.models.User.save"
	FQN string

	// StartLine is the first line of the function definition (1-indexed)
	// Includes decorators if present
	StartLine int

	// EndLine is the last line of the function body (1-indexed)
	EndLine int

	// SourceCode is the complete function source code
	// Includes decorators, signature, and body
	SourceCode string

	// LOC is lines of code (EndLine - StartLine + 1)
	LOC int

	// HasDecorators indicates if function has decorators (@property, @classmethod, etc.)
	HasDecorators bool

	// ClassName is the containing class name (if method), empty if top-level function
	// Example: "User" for myapp.models.User.save
	ClassName string

	// IsMethod indicates if this is a class method (has self/cls parameter)
	IsMethod bool

	// IsAsync indicates if this is an async function
	IsAsync bool
}

// LLMAnalysisResult contains the LLM's analysis of a function.
type LLMAnalysisResult struct {
	// FunctionFQN identifies which function was analyzed
	FunctionFQN string

	// DiscoveredPatterns contains sources/sinks/sanitizers found by LLM
	DiscoveredPatterns DiscoveredPatterns

	// DataflowTestCases are test cases generated by LLM
	// Each test case specifies expected dataflow behavior
	DataflowTestCases []DataflowTestCase

	// VariableTracking shows how LLM traced variables through the function
	VariableTracking []VariableTrack

	// Metadata about the analysis
	AnalysisMetadata AnalysisMetadata
}

// DiscoveredPatterns contains all patterns discovered by LLM in the function.
type DiscoveredPatterns struct {
	Sources     []PatternLocation
	Sinks       []PatternLocation
	Sanitizers  []PatternLocation
	Propagators []PropagatorOperation
}

// PatternLocation describes where a pattern (source/sink/sanitizer) was found.
type PatternLocation struct {
	// Pattern is the code pattern (e.g., "request.GET", "os.system")
	Pattern string

	// Lines where this pattern appears
	Lines []int

	// Variables involved
	Variables []string

	// Category for semantic grouping
	// Examples: "user_input", "file_read", "sql_execution", "command_exec"
	Category string

	// Description of what this pattern does
	Description string

	// Severity (for sinks): CRITICAL, HIGH, MEDIUM, LOW
	Severity string
}

// PropagatorOperation describes how data propagates.
type PropagatorOperation struct {
	// Type: "assignment", "function_call", "return"
	Type string

	// Line number
	Line int

	// Source variable
	FromVar string

	// Destination variable
	ToVar string

	// Function name (if Type == "function_call")
	Function string
}

// DataflowTestCase is a test case generated by LLM.
// This is what we validate our tool against.
type DataflowTestCase struct {
	// TestID for reference
	TestID int

	// Description of what this test validates
	Description string

	// Source information
	Source TestCaseSource

	// Sink information
	Sink TestCaseSink

	// Flow path (sequence of variables/operations)
	FlowPath []FlowStep

	// Sanitizers in the path (if any)
	SanitizersInPath []string

	// Expected detection result
	// true: Our tool SHOULD detect this flow
	// false: Our tool should NOT detect (e.g., sanitized)
	ExpectedDetection bool

	// Vulnerability type (if ExpectedDetection == true)
	VulnerabilityType string

	// Confidence score (0.0-1.0)
	Confidence float64

	// Reasoning for this test case
	Reasoning string
}

// TestCaseSource describes the source in a test case.
type TestCaseSource struct {
	Pattern  string // e.g., "request.GET['cmd']"
	Line     int
	Variable string
}

// TestCaseSink describes the sink in a test case.
type TestCaseSink struct {
	Pattern  string // e.g., "os.system"
	Line     int
	Variable string
}

// FlowStep describes one step in a dataflow path.
type FlowStep struct {
	Line      int
	Variable  string
	Operation string // "source", "assignment", "call", "sanitizer", "sink"
}

// VariableTrack shows how LLM traced a variable.
type VariableTrack struct {
	Variable      string
	FirstDefined  int
	LastUsed      int
	Aliases       []string // Other variable names that hold the same data
	FlowsToLines  []int
	FlowsToVars   []string
}

// AnalysisMetadata contains metadata about the LLM analysis.
type AnalysisMetadata struct {
	TotalSources    int
	TotalSinks      int
	TotalSanitizers int
	TotalFlows      int
	DangerousFlows  int
	SafeFlows       int
	Confidence      float64
	Limitations     []string
	ProcessingTime  string
	ModelUsed       string
}
