name: Publish VSCode Extension

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'extension/**'

jobs:
  publish-extension:
    if: |
      github.event.pull_request.merged == true &&
      (contains(github.event.pull_request.labels.*.name, 'release') ||
       contains(github.event.pull_request.labels.*.name, 'pre-release-publish')) &&
      contains(github.event.pull_request.labels.*.name, 'publish-vscode')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: extension/secureflow

      - name: Get current version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        working-directory: extension/secureflow

      - name: Check if pre-release
        id: check_prerelease
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'pre-release-publish') }}" == "true" ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "Pre-release mode enabled"
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "Regular release mode"
          fi

      - name: Check for existing version
        id: check_version
        run: |
          echo "Checking if version ${VERSION} exists in VSCode Marketplace..."
          curl -s https://marketplace.visualstudio.com/_apis/public/gallery/publishers/codepathfinder/vsextensions/secureflow/${VERSION} > /dev/null
          if [ $? -eq 0 ]; then
            echo "Version ${VERSION} already exists in VSCode Marketplace"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version ${VERSION} does not exist in VSCode Marketplace"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Package Extension
        if: steps.check_version.outputs.exists == 'false'
        run: |
          if [[ "${{ steps.check_prerelease.outputs.is_prerelease }}" == "true" ]]; then
            vsce package --pre-release
          else
            vsce package
          fi
        working-directory: extension/secureflow

      - name: Publish to VSCode Marketplace
        if: steps.check_version.outputs.exists == 'false'
        run: |
          if [[ "${{ steps.check_prerelease.outputs.is_prerelease }}" == "true" ]]; then
            vsce publish --pre-release
          else
            vsce publish
          fi
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        working-directory: extension/secureflow

      - name: Publish to Open VSX Registry
        if: steps.check_version.outputs.exists == 'false'
        run: |
          if [[ "${{ steps.check_prerelease.outputs.is_prerelease }}" == "true" ]]; then
            npx ovsx publish --pre-release
          else
            npx ovsx publish
          fi
        env:
          OVSX_PAT: ${{ secrets.OPENVSCODE_MARKETPLACE_TOKEN }}
        working-directory: extension/secureflow
